export { default as Dashboard } from './Dashboard'
export { default as Settings } from './Settings'
export { default as Assets } from './Assets'
export { default as Workorders } from './Workorders'
export { pagesEn, pagesPtBr } from './locales'
